### GET
GET localhost:3001/products

###

### POST
POST localhost:3001/products
Content-Type: application/json

{
  "name": "Paleta de guitarra",
  "price": 13.99,
  "description": "A description of the new product",
  "sellerId": "ba286c33-8b41-49ca-a305-91c5802ad873"
}

###