### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=GoLand

### POST

POST localhost:3001/purchase
Content-Type: application/json

{
  "productId": "5f9d5b83-b7f5-4890-befb-2e2e9226a0dc",
  "sellerId": "ea8b56af-7198-4521-8204-6c05c1dd8b52",
  "buyerId": "c18a1fc2-2853-4cdd-b2d3-c87425e7b8fc"
}