POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@email.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "a41b6130-e2da-4c20-9d07-3041a2d24db4"
}

###

POST http://localhost:3000/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "972b6973-9967-4973-afda-b165ba865d04",
  "account_id_to": "114aee75-3eb9-413c-a942-6e2d322ecd2e",
  "amount": 50
}