POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@email.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "515eddf3-31db-4ed5-944b-363999363fdb"
}

###

POST http://localhost:3000/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "ee7c48e2-0f0f-48ce-8c74-e50ada0de94f",
  "account_id_to": "dfd87915-5732-460d-9975-4812794ec244",
  "amount": 50000
}