POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@email.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "097ba1db-f826-4aea-93af-bdb436d3a598"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "ebfd3fca-9256-48f0-a0ba-8ca996c0f2c3",
  "account_id_to": "c8e7a567-743d-4b46-af41-c1b76d6e8034",
  "amount": 50
}